<template>
  <div>
    我是switch 文档
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
  </div>
</template>